apiVersion: infrastructure.greenlabs.io/v1alpha1
kind: PLCMachine
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-plc
    app.kubernetes.io/managed-by: kustomize
  name: plcmachine-sample
spec:
  # TODO(user): Add fields here
